# Site settings
title: A world with dragons
email: shuyang.li.95@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Written with &lt;3 by Shuyang Li. Powered by Jekyll.
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://shuyang.li" # the base hostname & protocol for your site
twitter_username: shuyangl
github_username:  shuyangli

# Build settings
markdown: kramdown
