# Site settings
title: A world with dragons
email: shuyang.li.95@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Shuyang's personal blog, built with <3 using Jekyll and served thru GitHub Pages.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://shuyang.li" # the base hostname & protocol for your site
twitter_username: shuyangl
github_username:  shuyangli
google_analytics:

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5